import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HeroComponent from "../components/HomePageComponents/HeroComponent"
import BestSellingProducts from "../components/HomePageComponents/BestSellingProducts"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HeroComponent />
        <BestSellingProducts/>
      </main>


    </>
  )
}
